<?php
/**
 * WDCA - Sweet Tooth
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the WDCA SWEET TOOTH POINTS AND REWARDS 
 * License, which extends the Open Software License (OSL 3.0).
 * The Sweet Tooth License is available at this URL: 
 *      http://www.wdca.ca/solutions_page_sweettooth/Sweet_Tooth_License.php
 * The Open Software License is available at this URL: 
 *      http://opensource.org/licenses/osl-3.0.php
 * 
 * DISCLAIMER
 * 
 * By adding to, editing, or in any way modifying this code, WDCA is 
 * not held liable for any inconsistencies or abnormalities in the 
 * behaviour of this code. 
 * By adding to, editing, or in any way modifying this code, the Licensee
 * terminates any agreement of support offered by WDCA, outlined in the 
 * provided Sweet Tooth License. 
 * Upon discovery of modified code in the process of support, the Licensee 
 * is still held accountable for any and all billable time WDCA spent 
 * during the support process.
 * WDCA does not guarantee compatibility with any other framework extension. 
 * WDCA is not responsbile for any inconsistencies or abnormalities in the
 * behaviour of this code if caused by other framework extension.
 * If you did not receive a copy of the license, please send an email to 
 * contact@wdca.ca or call 1-888-699-WDCA(9322), so we can send you a copy 
 * immediately.
 * 
 * @category   [TBT]
 * @package    [TBT_Rewards]
 * @copyright  Copyright (c) 2009 Web Development Canada (http://www.wdca.ca)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
*/

/**
 * Product Predict Points
 *
 * @category   TBT
 * @package    TBT_Rewards
 * @author     WDCA Sweet Tooth Team <contact@wdca.ca>
 */
?>

<?php 
	$points_adjusted_array = $this->getPredictedPoints();
?>
<div class="points-prediction">
    <?php if($this->doShowAsLowAs()): ?>
	<?php if(isset($points_adjusted_array['points_string']) && $points_adjusted_array['points_string'] != "") :?>
	    <?php if($points_adjusted_array['points_price'] === Mage::helper('core')->formatCurrency(0)) :?>
		<div class="as_low_as free_with_points">
	        <?php echo $this->__("Free using <b>%s!</b>",$points_adjusted_array['points_string']); ?>
	    </div>
	    <?php else :?>
		<div class="as_low_as">
	        <?php echo $this->__("As low as <b>%s</b> using <b>%s</b>" ,$points_adjusted_array['points_price'],$points_adjusted_array['points_string']); ?>
	    </div>
	    <?php endif ?>
	<?php endif ?>
	<?php endif; ?>
	<?php if($this->hasEarnablePoints() && !($this->getHideEarning())) :?>
    	<?php if($this->doGraphicalEarning()): ?>        
    		<div class="earnable" align="left">
    		    <table border=0 cellspacing=0 cellpadding=0><tbody><tr>
    		    	<td align="left" class="rewards-mini-icon-holder">
    				<img src="<?php echo $this->getSkinUrl("images/rewards/add_points.png"); ?>">
    			</td>
                  <td align="left">
                    <?php echo $this->__("Earn %s", $this->getEarnablePointsString()); ?>
                  </td>
                </tr></tbody></table>
            </div>
    	<?php else: ?>
    		<div class="earnable">
            <?php echo $this->__("Earn %s", $this->getEarnablePointsString()); ?>
            </div>
    	<?php endif ?>
	<?php endif ?>
	<!--<?php echo $this->getProduct()->getId(); /* This is here to differentiate each product display so that we don't think it's already been printed out during auto-integration */ ?>-->
</div>

