<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3><?php echo Mage::helper('aitsys')->__($this->getTitle()) ?></h3></td></td>
         </tr>
    </table>
</div>
<div class="entry-edit">
    <?php echo $this->getInstructionsHtml(); ?>
    
    <?php echo $this->__('After the above actions are successfully fullfilled, please return to the Module installation and retry it.'); ?>
</div>