
<?php if ($this->canCheckout()):?>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('js/checkout.js') ?>"></script>
<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>

<?php $this->getA()?>
<?php // echo $this->getChildHtml("oneclickcartcheckout.billing")?>
<?php //echo $this->getChildHtml("shipping_method")?>
<?php // echo $this->getChildHtml("payment")?>


<div style="display:none">
<div id="customerLoginForm">
<?php echo $this->getChildHtml("customer_form_login")?>
</div>
</div>
 
 <span id="shipping:same_as_billing"></span>
<div id="one-check" style="width:980px;">
  <h1><?=$this->__("Checkout")?></h1>
    <form id="checkoutform" method="POST" action="<?php echo $this->getUrl('oneclickcartcheckout/checkout/saveOrder') ?>" >
   
    <ol class="opc">
    <table class="cart_checkout_table">
    <?php if (!$this->helper('customer')->isLoggedIn() ):?>
    	<tr>
    		<td colspan="2">  
    		 <div class="loginHelp"><?php echo $this->__("Already registered?")?>  <a  onclick="showLoginForm()"><?=$this->__("click here to log-in.")?></a></div>
    		</td>
    	</tr>
    <?php endif;?>
        <tr>
            <td class="billing_section">
                <li class="section active">
					<div class="step-title">
					                <h2><?=$this->__("Billing Address")?></h2>

					            </div>
					<div class="step">
						<h3>Billing Address</h3>
                    <?=$this->getChildHtml("oneclickcartcheckout.billing")?> 

                    <?php echo $this->getChildHtml("shipping2")?>    
                    </div>
					</div>
                      </li> 

			  	<li class="section active">
					<div class="step-title">
					                <h2><?=$this->__("Payment and Delivery Method")?></h2>
					            </div>
					<div class="step">
				
                    <?=$this->getChildHtml("payment")?>
					<h3>Delivery Preference</h3>    
	                <?=$this->getChildHtml("shipping_method")?>
					</div>
                </li>
		
            </td>

			<td>
            <div>
				<div class="step-title">
				                <h2><?php echo $this->__('Order Review') ?></h2>
				            </div>
            <?php echo $this->getChildHtml("review")?>
<!--                 <div id='checkoutloader' class='checkoutloader' style="width:100%;height:150px"></div> -->

              <li class="section active section-coupon" id="coupon-section">
                 <?=$this->getChildHtml("coupon2")?>
                        </li>
            </div>
            
           </td>
        </tr>
    </table>
    
    </ol>
    </form>

    
    <script type="text/javascript">
    //<![CDATA[
    Event.observe(window, 'load', function() {
        var shippingMethod = new ShippingMethod('co-shipping-method-form', "<?php echo $this->getUrl('oneclickcartcheckout/checkout/saveShippingMethod') ?>");
    });

    updateCartUrl = "<?php echo $this->getUrl('oneclickcartcheckout/checkout/updateCart') ?>";

    Event.observe(window, 'load', function() {
       
  });
    
   function toggleShipping(){
        
       $("shipping-info").toggle();
        
    }

   	function showLoginForm(){
	  	 Modalbox.show($('customerLoginForm'),{title:"<?=$this->__("Customer Login")?>"});
	  	 setTimeout(function(){  new VarienForm('login-form', true);},1000);
	 }
    //]]>
    
    </script>
    </div>

	<section id="commentsRelated">
	 	<section id="related" class="container">
	 	<h2>Wear it with</h2>
	                <?php echo $this->getChildHtml('crosssell') ?>
	 	</section>
    <?php endif;?>