<?php
$_coreHelper = $this->helper('core');
$checkoutHelper = Mage::helper('onestepcheckout/checkout');

if (!$checkoutHelper->canRun()) {
    echo base64_decode('PGRpdiBzdHlsZT0iYm9yZGVyOiAzcHggc29saWQgcmVkOyBwYWRkaW5nOiA1cHg7IG1hcmdpbi1ib3R0b206IDE1cHg7IG1hcmdpbi10b3A6IDE1cHg7Ij5QbGVhc2UgZW50ZXIgYSB2YWxpZCBzZXJpYWwgZm9yIE9uZVN0ZXBDaGVja291dCBpbiB5b3VyIGFkbWluaXN0cmF0aW9uIHBhbmVsLiBJZiB5b3UgZG9uJ3QgaGF2ZSBvbmUsIHBsZWFzZSBwdXJjaGFzZSBhIHZhbGlkIGxpY2Vuc2UgZnJvbSA8YSBocmVmPSJodHRwOi8vd3d3Lm9uZXN0ZXBjaGVja291dC5jb20iPnd3dy5vbmVzdGVwY2hlY2tvdXQuY29tPC9hPjwvZGl2Pg==');
} else {
    ?>

    <table class="onestepcheckout-summary">
        <thead>
            <tr>
                <th class="name"><?php echo $this->__('Product'); ?></th>
                <th class="qty"><?php echo $this->__('Qty'); ?></th>
                <th class="total"><?php echo $this->__('Subtotal'); ?></th>
            </tr>
        </thead>
        <?php foreach ($this->getItems() as $item): ?>
            <tr>
                <td class="name"><?php echo $item->getName(); ?></td>
                <td class="qty"><?php echo $item->getQty(); ?></td>
                <td class="total">
                    <?php /* Show prices without tax */ ?>
                    <?php echo $this->helper('checkout')->formatPrice($item->getRowTotal()); ?>

                    <?php /* Show prices with tax */ ?>
                    <?php /* echo $this->helper('checkout')->formatPrice($this->helper('checkout')->getPriceInclTax($item)); */ ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>

    <table class="onestepcheckout-totals">
        <?php echo $this->renderTotals(); ?>
        <?php echo $this->renderTotals('footer'); ?>
    </table>

<?php } ?>