<?php $file = $this->getFile() ?>
<?php if($file): ?>
	<!--&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	<input type="checkbox" id="file_delete" class="checkbox" value="1" name="source_file[delete]">
	<?php echo $this->__('Delete File') ?>
	<br/>-->
	<embed width="<?php echo $this->getWidth()?>" height="<?php echo $this->getHeight() ?>"
		pluginspage="http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash" 
		type="application/x-shockwave-flash" 
		wmode="transparent" 
		quality="high" src="<?php echo $file ?>" 
	name="banner">
<?php endif; ?>