<?php

/**
* aheadWorks Co.
*
* NOTICE OF LICENSE
*
* This source file is subject to the EULA
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://ecommerce.aheadworks.com/LICENSE-M1.txt
*
* @category   AW
* @package    AW_Rma
* @copyright  Copyright (c) 2010 aheadWorks Co. (http://www.aheadworks.com)
* @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
*/
?>

<?php if($this->getComments()->getSize()) : ?>
<ul class="awrma-comments-list">
<?php foreach($this->getComments() as $_comment) : ?>
    <li>
        <strong>
            <?php echo $this->formatDate($_comment->getCreatedAt()) ?> <?php echo $this->formatTime($_comment->getCreatedAt()) ?>
            <span class="separator">|</span>
            <?php if($_comment->getOwner() == AW_Rma_Model_Source_Owner::ADMIN) : ?>
            <?php echo Mage::getModel('awrma/source_owner')->getOptionLabel($_comment->getOwner()) ?>
            <?php else : ?>
            <?php echo $this->getRmaRequest()->getCustomerName() ?>
            <?php endif ?>
        </strong>
        <div><?php echo $_comment->getText() ?></div>
        <?php if($_comment->getAttachments()) : ?>
        <div>
            <a href="<?php echo $this->getUrl('awrma/adminhtml_rma/download', array('cid' => $_comment->getId())) ?>"><?php echo $_comment->getAttachments() ?></a> (<?php echo Mage::helper('awrma/files')->getTextSize($_comment->getAttachments()) ?>)
        </div>
        <?php endif ?>
    </li>
<?php endforeach ?>
</ul>
<?php else : ?>
<?php echo $this->__('No comments yet') ?>
<?php endif ?>
