<div class="referrals">
    
        <h1>Invite a Friend</h1>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_referred = $this->getReferred();?>

<br/>
<?php 
	$referrerCount = count($_referred);
	$referrerPercent = $referrerCount * 10;
?>

<span id="referralBar"><span id="numReferrals" style="width=<?php echo $referrerPercent; ?>%"></span></span>

<div class="half-col right"><?php echo $this->getChildHtml('affiliate'); ?></div>
<?php echo $this->getChildHtml('refer_form'); ?>
<?php //echo $this->getChildHtml('preferences'); ?>
<div class="clear"></div>
<br />
<?php echo $this->getChildHtml('history'); ?>

</div>