<div class="right" id="help">
	<a href="/contacts" class="needAssistance2 fr" title="Need Assitance? Talk to a live rep"><img src="<?php echo $this->getSkinUrl('images/icons/question-mark.png'); ?>" alt="Question mark icon"> Need Assistance</a>
	</div>

<div class="referrals">
    
        <h1>Invite a Friend</h1>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<div class="half-col right"><?php echo $this->getChildHtml('affiliate'); ?></div>
<?php echo $this->getChildHtml('refer_form'); ?>
<?php //echo $this->getChildHtml('preferences'); ?>
<div class="clear"></div>
<br />
<?php echo $this->getChildHtml('history'); ?>

</div>