    <div id="bannerslider" <?php if($home_page):?>class="fixedHeader" <?php endif;?>>
    	<?php 
    	$gender=$_SESSION['selected_gender'];
    	if($gender!='')
		{
			if($gender=='men')
			  $gendercode=array(1,2);
			elseif($gender=='women')
			  $gendercode=array(1,3);
			else 
			  $gendercode=array(1,2,3);
			
			$banner_images=Mage::getModel('banner/banner')->getCollection()->addFieldToFilter("banner_type",3)->addFieldToFilter("gender",array('in'=>$gendercode))->setOrder('gender','desc')->getData();
		}
		else {
			$banner_images=Mage::getModel('banner/banner')->getCollection()->addFieldToFilter("banner_type",3)->setOrder('gender','desc')->getData();
		}
		
		
		?>
    	
        
    	<ul class="mainBannerslider">
        	<?php 
			foreach ($banner_images as $banner_image)
			{?>
				<li>
                	 <a href="<?php echo $banner_image['link']?>"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'Banners/images/'.$banner_image['bannerimage'];?>"/></a>
                </li>
			<?php }
            ?>
		</ul>
        </div><!-- end: bannerslider -->      
    <!-- end: nks code -->