<?php
$tweets=$this->getTweetes(); 
 ?>
 <!-- nks code starts -->
<div class="tweetSliderWrapper">
<div class="mainSprite twtIcon"></div>
<button class="btnPurp2">FOLLOW US</button>
    	
   	  <ul class="tweetSlider">
       	 
       	  <?php 
			foreach ($tweets as $tweet)
			{
				foreach($tweet->entities->urls as $urls)
				{
					$text=str_replace($urls->url, "<a href='".$urls->url."'>".$urls->display_url."</a>", $tweet->text);
				}
				$tweet_date=$tweet->created_at;
			   echo "<li class='tweet_li'>";
 						echo $text;
 						echo "<span class='screenName'>@".$tweet->user->screen_name."</span>";
 						echo "<span class='timeLapse'>".date('d M',strtotime($tweet_date))."</span>";
				echo "</li>";
				
			}
            ?>
	  </ul>
    </div> 
<script>
    		jQuery(document).ready(function()
							{
  								jQuery('.tweetSlider').bxSlider();
							}
						 );
    	</script>      
    <!-- end: nks code -->
