<?php
/**
 * Affiliate's navigation template
 */
?>
<div class="block block-account">
    <div class="block-title">
        <strong><span><?php echo $this->getNavigationTitle(); ?></span></strong>
    </div>
    <div class="block-content">
        <ul id="affiliateplus-navigation-<?php echo $this->getNameInLayout() ?>">
            <?php $_links = $this->getLinks(); ?>
            <?php foreach ($_links as $_link): ?>
            	<?php if ($_link->getDisabled()) continue; ?>
                <?php if ($this->isActive($_link)): ?>
                    <li class="current"><strong><?php echo $_link->getLabel() ?></strong></li>
                <?php else: ?>
                    <li><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
        <script type="text/javascript">
        	decorateGeneric($('affiliateplus-navigation-<?php echo $this->getNameInLayout() ?>').childElements(),['last']);
        </script>
    </div>
</div>