<div class="referrals">
    <div class="page-title">
        <h1><?php echo $this->__('Invite a Friend') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<div class="half-col right"><?php echo $this->getChildHtml('affiliate'); ?></div>
<?php echo $this->getChildHtml('refer_form'); ?>
<?php //echo $this->getChildHtml('preferences'); ?>
<div class="clear"></div>
<br />
<?php echo $this->getChildHtml('history'); ?>

</div>