<div class="step-title">
            <span class="number">2</span>
                <h2><?=$this->__("Payment Methods")?></h2>
            </div>
<div class="step">
  <fieldset>
        <?php echo $this->getChildHtml('methods') ?>
    </fieldset>
    </div>
<script type="text/javascript">
<!--

$$('#checkout-payment-method-load dt input').invoke('observe', 'click', function(e) {
    var element = e.element();
    var name = 'payment_form_' + element.value;
    $$('dd.payment-method').invoke('hide');
    if(element.checked) {
        var form = $(name);
        var container = $('container_payment_method_' + element.value);
        if(element !== null && container !== null)    {
            container.show();
            $(name).show();
        }
    }    
});
//-->
</script>    
    
  