
<div class="step-title">
            <span class="number">2</span>
                <h2><?=$this->__("Select Payment Method")?></h2>
            </div>
<div class="step">

<script type="text/javascript">
//<![CDATA[
    //var payment = new Payment('co-payment-form', '<?php echo $this->getUrl('checkout/onepage/savePayment') ?>');
    var payment = new Payment('co-payment-form', '<?php echo $this->getUrl('oneclickcartcheckout/checkout/savePaymentMethod') ?>');
//]]>
</script>

    <fieldset>
        <?php echo $this->getChildHtml('methods') ?>
    </fieldset>

<div class="tool-tip" id="payment-tool-tip" style="display:none;">
    <div class="btn-close"><a href="#" id="payment-tool-tip-close" title="<?php echo $this->__('Close') ?>"><?php echo $this->__('Close') ?></a></div>
    <div class="tool-tip-content"><img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" title="<?php echo $this->__('Card Verification Number Visual Reference') ?>" /></div>
</div>

<script type="text/javascript">
//<![CDATA[
    function toggleToolTip(event){
        if($('payment-tool-tip')){
            $('payment-tool-tip').setStyle({
                top: (Event.pointerY(event)-560)+'px'//,
                //left: (Event.pointerX(event)+100)+'px'
            })
            $('payment-tool-tip').toggle();
        }
        Event.stop(event);
    }
    if($('payment-tool-tip-close')){
        Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
    }
//]]>
</script>
<script type="text/javascript">
//<![CDATA[
    payment.currentMethod = "<?php echo $this->getChild('methods')->getSelectedMethodCode() ?>";
//]]>
</script>
</div>
