
    <?php $_referred = $this->getReferred();?>
   
<?php if($this->showHistory()): ?>
<br/><br/>    
<h3 class="page-invite-head fl">Track Your Progress</h3>

	<br/>
	<?php 
		$referrerCount = count($_referred);
		$referrerPercent = $referrerCount * 10;
		$awayFrom10 = 10 - $referrerCount;
	?>
	<h3 class="fr" id="howClose"><?php echo $awayFrom10 ?> more friends until a special prize!</h3>
	<span id="referralBar" class="clear"><span id="numReferrals" style="width:<?php echo $referrerPercent; ?>%;"></span></span>
	
    <?php if($_referred->getSize()): ?>
    <table cellspacing="0" class="data-table" id="referred-friends-table">
        <thead>
            <tr>
                <?php ?><th><?php echo $this->__('Full Name') ?></th><?php ?>
                <th><?php echo $this->__('Email') ?></th>
                <!--<th><?php echo $this->__('Registered?') ?></th>-->
                <th><?php echo $this->__('Status') ?></th>
                <th><?php echo $this->__('Earnings') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php $_odd = ''; ?>
            <?php foreach ($_referred as $_friend): ?>
                <tr>
                    <?php ?><td><?php echo $_friend->getReferralName() ?></td><?php ?>
                    <td><?php echo $_friend->getReferralEmail() ?></td>
                    <!--<td><?php echo $_friend->getReferralChildId() ? $this->__('yes') : $this->__('no') ?></td>-->
                    <td class="a-left"><?php echo $this->getStatusCaption( (int)($_friend->getReferralStatus()) ); ?></td>
                    <td><?php echo $this->getAccumulatedReferralPoints($_friend); ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <script type="text/javascript">decorateTable('referred-friends-table')</script>
    <?php else: ?>
        <p><?php echo $this->__("You don't have any referrals yet."); ?></p>
    <?php endif ?>
<?php endif ?>