
    <?php $_referred = $this->getReferred();
		$numSignedUp=0;
		foreach ($_referred as $_friend):
			if((int)($_friend->getReferralStatus()) ==1){
				$numSignedUp++;
			}
		endforeach;
	?>
   
<?php if($this->showHistory()): ?>
<br/><br/>    
<h3 class="page-invite-head fl">Track Your Progress</h3>

	<br/>
	<?php 
		$referrerCount = count($_referred);
		$referrerPercent = $referrerCount * 10;
		if($referrerPercent>100){$referrerPercent=100;}
		$awayFrom10 = 10 - $referrerCount;
		//echo $numSignedUp;
	?>
	<h3 style="margin-left:50px" class="fr" id="howClose"><?php if($referrerCount > 9){ echo "Congratulations. You just earned Rs. 500. Use coupon code <span>ROFSVIPOJA</span> at checkout."; }else{ ?>Invite <?php echo $awayFrom10 ?> more friends to get Free Rs. 500.<?php } ?><br>Bonus: Rs. 500 credit when your friend makes first Rs. 500 purchase within 30 days of joining.</h3>
	<span id="referralBar" class="clear"><span id="numReferrals" style="width:<?php echo $referrerPercent; ?>%;"></span></span>
  
<?php endif ?>