<?php if (Mage::getStoreConfigFlag('catalog/frontend/useajaxscroll')): ?>
<?php 
// Get the default setting for grid or list mode
$productListMode = Mage::getStoreConfig('catalog/frontend/list_mode');
if ($productListMode == 'grid-list')
	$productListMode = 'grid';
elseif ($productListMode == 'list-grid')
	$productListMode = 'list';

// Check if this setting is overwritten by the user
if ($this->getRequest()->getParam('mode')) {
	if($this->getRequest()->getParam('mode') == 'grid')
		$productListMode = 'grid';
	else
		$productListMode = 'list';
}
?>
<script type="text/javascript">
jQuery.ias({
	container : '#saleProducts',
	<?php if ($productListMode == 'grid'): ?>
	item: '.product',
	<?php else: ?>
	item: '.products-list',
	<?php endif; ?>
	pagination: '.toolbar-bottom',
	next: '.next',
	tresholdMargin : -700,
	loader: '<div style="display:block;clear:both;height:30px;width:100%;"><img src="<?php echo($this->getSkinUrl('images/ajaxscroll/loader.gif')); ?>" /> <?php echo __('Loading more products, please be patient...'); ?></div>',
	onRenderComplete : function(items) { 
	      jQuery(".product").hover(function () {
		    jQuery(this).find('.productName').fadeIn(500);
		  }, 
		  function () {
		    jQuery(this).find('.productName').fadeOut(500);
		  });
	}
});
</script>
<?php endif; ?>
