<?php if (Mage::getStoreConfigFlag('catalog/frontend/useajaxscroll')): ?>

<?php 

// Get the default setting for grid or list mode

$productListMode = Mage::getStoreConfig('catalog/frontend/list_mode');

if ($productListMode == 'grid-list')

	$productListMode = 'grid';

elseif ($productListMode == 'list-grid')

	$productListMode = 'list';



// Check if this setting is overwritten by the user

if ($this->getRequest()->getParam('mode')) {

	if($this->getRequest()->getParam('mode') == 'grid')

		$productListMode = 'grid';

	else

		$productListMode = 'list';

}

?>

<script type="text/javascript">

jQuery.ias({

	container : '#saleProducts',

	<?php if ($productListMode == 'grid'): ?>

	item: '.product',

	<?php else: ?>

	item: '.products-list',

	<?php endif; ?>

	pagination: '.toolbar-bottom',

	next: '.next',

	history: false,

	loader: '<div style="display:block;clear:both;height:30px;width:100%;"><img src="<?php echo($this->getSkinUrl('images/loading.gif')); ?>" width="20"/> </div>',

	triggerPageThreshold: 150,

	thresholdMargin: 0,

	loader: '<div style="display:block;clear:both;height:30px;width:100%;"><img src="<?php echo($this->getSkinUrl('images/Loading_rooja.gif'));  ?>" width="30" /><br><br>Hang on! Loading more products...</div>',

	onRenderComplete : function(items) { 

	      jQuery(".product").hover(function () {

		    jQuery(this).find('.productName').fadeIn(500);
			jQuery(this).find('.fb-like').show();

		  }, 

		  function () {

		    jQuery(this).find('.productName').fadeOut(500);
			jQuery(this).find('.fb-like').hide();

		  });


        jQuery('img.lazy').jail({
                effect       : "fadeIn"
        });

	}

});

</script>
<script>
jQuery(document).ajaxComplete(function(){
    try{
        FB.XFBML.parse(); 
    }catch(ex){}
});
</script>

<?php endif; ?>

