<?php
/**
 * Popup Header
 */
?>
<div class="content-header">
    <h3><?php echo $this->__('Select upper tier affiliate') ?></h3>
    <div class="affiliateplus-close-tinybox" style="cursor: pointer; color: #D00; float: right; font-weight: bold;" onclick="TINY.box.hide();">
        <span title="<?php echo $this->__('Close') ?>"><?php echo $this->__('Close') ?> [X]</span>
    </div>
</div>
