<?php

$step_counter = 1;
$helper = Mage::helper('onestepcheckout/checkout');

?>
<style type="text/css">
.pname {
	padding:3px!important;
	margin:3px!important;
}

.fancybox-inner {
	overflow:hidden!important;
}
#sendmail {
    background: none repeat scroll 0 0 #431F4C;
    border: medium none;
    color: #FFFFFF;
    cursor: pointer;
    font: 12px/30px Arial,Helvetica,sans-serif;
    height: 30px;
    padding: 2px 10px;
    text-align: center;
}
#zipcode_container {
	font-family:Arial, Helvetica, sans-serif!important;
	font-size:12px!important;
	margin:2px!important;
	line-height:12px!important;
}
#zipcodewelcomemessage {
	width:650px!important;
}
.inputfield {
	border: 1px solid #CCCCCC;
    height: 18px;
    width: 135px;
}
.product_container {
	border: 1px solid #CCCCCC;
    display: block;
    overflow: hidden;
    padding: 7px;
    position: relative;
    width: 630px;
	margin-top: 18px;
}
.fancybox-inner {
	height:auto!important;
}
</style>
<script>
(function ($) {
	$(document).ready(function(){
	
		$(".payment-methods input").live('change', function() {
			
			if($('#p_method_cashondelivery').is(':checked')) { 
				$("#container_payment_method_cashondelivery").css("display", "block");
				
				$("#hintText").html('We verify all Cash on Delivery orders over the phone after you have made a purchase and start processing the order. Our customer service team will contact you within 24 hours and alternatively you can call us at +91-8080622277 to verify your order. Failing verification of the order will result in a cancellation. Failure to accept a verified order will revoke your Cash On Delivery privileges on future orders. <br><br>The maximum limit for a COD order is Rs 20,000 outside of New Delhi and Gurgaon.');
				$("#hintImg").html('<img src="<?php echo $this->getSkinUrl('images/cod.png'); ?>" alt="Security" id="secureLogos">');
			}
			if($('#p_method_Avenues_standard').is(':checked')) { 
				$("#container_payment_method_cashondelivery").css("display", "none");
				
				$("#hintText").html('You will be redirected to CCAvenue our secure online payment-processing partner.');
				$("#hintImg").html('<img src="<?php echo $this->getSkinUrl('images/veri-2.png'); ?>" alt="Security" id="secureLogos">');
			}
			
						
		});

		$("#azcodelink").fancybox({
			'scrolling'     : 'no',
			'titleShow'     : false,
			'onClosed'      : function() {		
				//$("#login_error").hide();
			}
		});
		$("#sendmail").click(function () {
			var e = document.forms['zipcode_form'].elements;
			var ret = 'true';
			if(e['name'].value == '') {
				alert("Please enter the Name");
				e['name'].focus();
				ret = 'false';
			}
			if(e['email'].value == '' && ret == 'true') {
				alert("Please enter the Email");
				e['email'].focus();
				ret = 'false';
			}
			if(e['email'].value != '' && ret == 'true') {
				var uemail = e['email'].value
				if (validateEmail(uemail)) {
					
				} else {
					alert("Please enter valid Email");
					e['email'].focus();
					ret = 'false';
				}
			}
			if(e['mobile'].value == '' && ret == 'true') {
				alert("Please enter the Mobile");
				e['mobile'].focus();
				ret = 'false';
			}
			if(e['pincode'].value == '' && ret == 'true') {
				alert("Please enter the Pincode");
				e['pincode'].focus();
				ret = 'false';
			}
			if(ret == 'false') {
				return false;
			} else {
				uname = e['name'].value;
				email = e['email'].value;
				mobile = e['mobile'].value;
				pincode = e['pincode'].value;
				
				$.ajax({ 
					url: "<?php echo Mage::getURL('') ?>/fileupload/Zipcodemail/zipcodemailsend", 
					context: document.body, 
					data: "uname="+uname+"&email="+email+"&mobile="+mobile+"&pincode="+pincode,
					success: function(res){
						e['name'].value = e['email'].value = e['mobile'].value = e['pincode'].value = '';
						if(res == 'true') {
							
							var thanks_msg = '<p style="color:green">Thanks. We received your Zip code, we will check it and get back to you.</p>';
							$("#zipcode_mail_message").html(thanks_msg);
							//$("#zipcode_container").delay(800);
							//parent.jQuery.fancybox.close();
							//setTimeout('parent.jQuery.fancybox.close();', '800');

						}
						
					}
				});
				return false
			}
		});
		
		$(".numbersonly").keydown(function(event) {
				// Allow: backspace, delete, tab, escape, and enter
				if ( event.keyCode == 46 || event.keyCode == 8 || event.keyCode == 9 || event.keyCode == 27 || event.keyCode == 13 || 
					 // Allow: Ctrl+A
					(event.keyCode == 65 && event.ctrlKey === true) || 
					 // Allow: home, end, left, right
					(event.keyCode >= 35 && event.keyCode <= 39)) {
						 // let it happen, don't do anything
						 return;
		} else {
					// Ensure that it is a number and stop the keypress
					if (event.shiftKey || (event.keyCode < 48 || event.keyCode > 57) && (event.keyCode < 96 || event.keyCode > 105 )) {
						event.preventDefault(); 
					}   
				}
		});
		
	});
})(jQuery);

function validateEmail(sEmail) {
    var filter = /^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$/;
    if (filter.test(sEmail)) {
        return true;
    }
    else {
        return false;
    }
}

</script>
<div style="display:none"><a id="azcodelink" href="#zipcode_container">test</a></div>
<?php
$items = Mage::getSingleton('checkout/session')->getQuote()->getAllItems();
?>
<div id="zipcode_container" style="display:none;">

<script language="javascript" type="text/javascript">
if(document.getElementById("billing:postcode")) {
	document.getElementById("billing:postcode").value = '';
	document.getElementById("billing:postcode").focus = '';
}
</script>
 
	<div id="zipcodewelcomemessage"><p>Thanks for shopping at Rooja!  We value your business.  Currently, our logistics partners have limitations servicing the entered pincode.  We are committed to having you experience Rooja.  Options - 1) Provide an alternate PIN code OR 2) Please submit your order request to Customer Care and someone will get back to you within 24-48 hours.</p></div>
	<div id="zipcode_mail_message"></div>
	<form name="zipcode_form" id="zipcode_form" method="post">
        <div style="width:650px; height:50px; position:relative">
            <div id="namefield" style="float:left; width:150px; height:50px;">
                <span style="font-weight:bold;">Name</span><br /><br />
                 <input type="text" name="name" id="name" value="" class="inputfield" /> 
            </div>
            <div id="emailfield" style="float:left; width:150px; height:50px; margin-left:15px;">
                <span style="font-weight:bold;">Email ID</span><br /><br />
               <input type="text" name="email" id="email" value="" class="inputfield" />
            </div>
            <div id="mobilefield" style="float:left; width:150px; height:50px; margin-left:15px;">
                <span style="font-weight:bold;">Mobile</span><br /><br />
                <input type="text" name="mobile" id="mobile" value=""class="inputfield" /> 
            </div>
             <div id="pincodefield" style="float:left; width:150px; height:50px; margin-left:15px;">
                <span style="font-weight:bold;">Pincode</span><br /><br />
               <input type="text" name="pincode" id="pincode" value="" class="inputfield numbersonly" /> 
            </div>
        </div>
        
        <div class="product_container">
            <div style="width:650px; position:absolute; height:30px;">
                <div id="pnameheading" style="width:370px; float:left; font-weight:bold;">Product Name</div>
                <div id="pqtyheading" style="width:140px; float:left; font-weight:bold;">Quantity</div>
                <div id="ptotheading" style="width:140px; float:left; font-weight:bold;">Total</div>
            </div>
           <div style="width:650px; padding-top:15px;">
            <?php 
            foreach($items as $item): 
                    if($item->getRowTotal() > 0) {
                    ?>
                    <div style="width:700px; padding-top:10px; position:relative">
                        <div class="pname" style="width:400px; float:left;"> <?php echo $item->getName()." - ".$item->getRowTotal(); ?>
                    <?php if($checkoutHelper->settings['show_custom_options']): ?>
                        <?php $options = $item->getProduct()->getTypeInstance(true)->getOrderOptions($item->getProduct()); ?>
                        <?php 
                        if (0) {
                            if(isset($options['options']) && count($options['options']) > 0): 
                        ?>
                                <ul class="onestepcheckout-custom-options">
                                    <?php foreach($options['options'] as $option): ?>
                                        <li><?php echo '<b>'.$option['label'] . ':</b> ' . $option['value']; ?></li>
                                    <?php endforeach; ?>
                                </ul>
                        <?php 
                            endif; 
                        } ?>
        
                        <?php if($item->getProduct()->isConfigurable()): ?>
        
                        <?php
                        $configurable_options = $item->getProduct()->getTypeInstance(true)->getSelectedAttributesInfo($item->getProduct());
                        ?>
        
                        <?php if(is_array($configurable_options) && count($configurable_options) > 0): ?>
                        <ul class="onestepcheckout-custom-options">
                        <?php foreach($configurable_options as $option): ?>
                            <li><b><?php echo $option['label']; ?>:</b> <?php echo $option['value']; ?></li>
                        <?php endforeach; ?>
                        </ul>
                        <?php endif; ?>
        
                        <?php endif; ?>
        
                    <?php endif; ?></div>
                        <div class="pqty" style="width:125px; float:left;"><?php echo $item->getQty(); ?></div>
                        <div class="pprice" style="width:125px; float:left;"> <?php if($checkoutHelper->settings['display_tax_included']): ?>
                    <?php echo $this->helper('checkout')->formatPrice($this->helper('checkout')->getSubtotalInclTax($item)); ?>
                    <?php else: ?>
                    <?php echo $this->helper('checkout')->formatPrice($item->getRowTotal()); ?>
                    <?php endif; ?></div>
                    </div>
                <?php 
                    } 
            endforeach; 
            ?>
            </div>
        </div>
        <div style="width:650px; position:relative; margin-top:15px;">
            <input type="button" name="sendmail" id="sendmail" value="Send Mail" />
        </div>
	</form>
</div>

<?php if(!$this->canCheckout() || !$this->validateMinimumAmount()): ?>
    <?php if($this->settings['checkout_title']): ?>
        <h1 class="onestepcheckout-title"><?php echo $this->settings['checkout_title']; ?></h1>
    <?php endif; ?>

    <?php if($this->canCheckout() && !$this->validateMinimumAmount()): ?>
    <p><?php echo Mage::getStoreConfig('sales/minimum_order/description'); ?></p>
    <p><a href="<?php echo $this->getUrl(''); ?>"><?php echo $this->__('Back to homepage'); ?></a></p>
    <?php else: ?>
    <p><?php echo $this->__('You need to have products in your cart to checkout, and your cart is empty.'); ?></p>
    <p><a href="<?php echo $this->getUrl(''); ?>"><?php echo $this->__('Back to homepage'); ?></a></p>
    <?php endif; ?>
<?php else: ?>

<form id="onestepcheckout-form" method="post" action="<?php echo $this->getUrl('onestepcheckout', array('_secure'=>true)); ?>">
<fieldset class="group-select" style="margin: 0;">

<?php if($this->settings['checkout_title']): ?>
    <h1 class="onestepcheckout-title"><?php echo $this->settings['checkout_title']; ?></h1>
<?php endif; ?>

<?php if($this->settings['checkout_description']): ?>
    <p class="onestepcheckout-description"><?php echo $this->settings['checkout_description']; ?></p>
<?php endif; ?>

<?php if(!$this->isCustomerLoggedIn() && $helper->showLoginLink()): ?>
    <p class="onestepcheckout-login-link">
        <a id="onestepcheckout-login-link" href="javascript:void(0);"><?php echo $this->__('Already registered? Click here to login.'); ?></a>
    </p>
<?php endif; ?>

<?php if(isset($this->formErrors['unknown_source_error'])): ?>
<div class="onestepcheckout-error">
    <?php echo $this->formErrors['unknown_source_error']; ?>
</div>
<?php endif; ?>

<div class="onestepcheckout-threecolumns checkoutcontainer onestepcheckout-skin-<?php echo $this->settings['skin']; ?> <?php if(Mage::helper('onestepcheckout')->isEnterprise()): ?>onestepcheckout-enterprise<?php endif; ?>">
    <div class="onestepcheckout-column-left">
        <div id="billing_address">
            <script type="text/javascript">
            var billing = new Billing();
            </script>
            <ul>
                <li>
                    <p class="onestepcheckout-numbers onestepcheckout-numbers-<?php echo $step_counter++; ?>"><?php echo $this->__('Billing address'); ?></p>
                        <?php if(isset($this->formErrors['billing_error']) && count($this->formErrors['billing_errors']) > 0): ?>
                        <div class="onestepcheckout-error">
                            <?php echo $this->__('Please check red fields below and try again.'); ?>
                        </div>
                        <?php endif; ?>
                </li>
                <?php if ($this->customerHasAddresses()): ?>
                <li>
                    <label for="billing-address-select"><?php echo $this->__('Select a billing address from your address book or enter a new address.') ?></label>
                    <div class="input-box">
                        <?php echo $this->getAddressesHtmlSelect('billing') ?>
                    </div>
                </li>


                <?php endif; ?>
                <li>
                    <div>
                        <ul id="billing_address_list" <?php echo (($this->customerHasAddresses() && !$this->getNewAddressSelectValueOnError('billing')) ? 'style = "display:none"' : false ); ?>>
							<!-- <li>Form container begin</li> -->
                            <?php echo $this->getChildHtml('billing_address');?>
                            <?php $addressAttributes = $this->getChild('customer_form_billing_address_user_defined_attributes');?>
                            <?php if ($addressAttributes): ?>
                                <?php $addressAttributes->setEntity($this->getQuote()->getBillingAddress())->setEntityType('customer_address');?>
                                <?php $addressAttributes->setFieldIdFormat('billing:%1$s')->setFieldNameFormat('billing[%1$s]');?>
                                <?php echo $addressAttributes->setExcludeFileAttributes(true)->setShowContainer(false)->toHtml()?>

                            <?php endif;?>
                            <?php $customerAttributes = $this->getChild('customer_form_customer_user_defined_attributes');?>
                            <?php if ($customerAttributes): ?>
                                <?php $customerAttributes->setEntityModelClass('customer/customer')->setFieldIdFormat('billing:%1$s');?>
                                <?php $customerAttributes->setFieldNameFormat('billing[%1$s]')->setShowContainer(false);?>
                                <?php echo $customerAttributes->setExcludeFileAttributes(true)->toHtml()?>
                            <?php endif;?>
							<!-- <li>Form container end</li> -->
                        </ul>
                    </div>
                </li>
                <li>
                    <?php $uncheck = (!empty($_POST['billing']) && empty($_POST['billing']['use_for_shipping']));?>
                    <?php if($this->differentShippingAvailable()): ?>
                        <div class="input-box input-different-shipping">
                            <input type="checkbox" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes" value="1" <?php echo (($this->sameAsBilling() && !$uncheck) ? 'checked="checked" ':'')?> class="sameasbilling" />
                            <label for="billing:use_for_shipping_yes"><?php echo $this->__('Ship to the same address')?></label>
                        </div>
                    <?php else: ?>
                        <input type="hidden" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes" value="1" />
                    <?php endif; ?>
                </li>
            </ul>
        </div>
    <?php if($this->differentShippingAvailable()): ?>
        <div id="shipping_address" <?php  echo (($this->sameAsBilling() && !$uncheck) ? 'style="display: none"': false);?>>
            <script type="text/javascript">
                var shipping = new Shipping();
            </script>
            <ul>
                <li class="shipping-address-title">
                    <?php echo $this->__('Shipping address'); ?>
                </li>
                <?php if ($this->customerHasAddresses()): ?>
                   <li class="form-alt">
                       <label for="shipping-address-select"><?php echo $this->__('Select a shipping address from your address book or enter a new address.') ?></label>
                       <div class="input-box"><?php echo $this->getAddressesHtmlSelect('shipping') ?></div>
                   </li>
                <?php endif ?>
                <li id="shipping_address_list" <?php if($this->customerHasAddresses() && !$this->getNewAddressSelectValueOnError('shipping')) { echo '  style="display: none;" '; } ?>>
                    <div id="">
                        <ul>
                            <?php echo $this->getChildHtml('shipping_address');?>
                            <?php $addressAttributes = $this->getChild('customer_form_shipping_address_user_defined_attributes');?>
                            <?php if ($addressAttributes): ?>
                                <?php $addressAttributes->setEntity($this->getQuote()->getShippingAddress())->setEntityType('customer_address');?>
                                <?php $addressAttributes->setFieldIdFormat('shipping:%1$s')->setFieldNameFormat('shipping[%1$s]');?>
                                <?php echo $addressAttributes->setExcludeFileAttributes(true)->setShowContainer(false)->toHtml()?>
                            <?php endif;?>
                        </ul>
                        <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getQuote()->getShippingAddress()->getId() ?>" id="shipping:address_id" />
                        <!-- END LIST OF SHIPPIING FIELDS -->
                    </div>
                </li>
            </ul>
        </div>
    <?php endif; ?>
</div>

    <div class="onestepcheckout-column-middle">


        <?php if(!$this->isVirtual()): ?>
            <?php if(Mage::getStoreConfig('onestepcheckout/general/hide_shipping_method')):?>
                <?php if(isset($this->formErrors['shipping_method']) && $this->formErrors['shipping_method']): ?>
                    <div class="onestepcheckout-error onestepcheckout-shipment-method-error">
                        <?php echo $this->__('Please choose a shipping method.'); ?>
                    </div>
                <?php endif; ?>
                <?php echo $this->getChildHtml('choose-shipping-method'); ?>
            <?php else:?>
                <div class="onestepcheckout-shipping-method">
                    <p class="onestepcheckout-numbers onestepcheckout-numbers-<?php echo $step_counter++; ?>"><?php echo $this->__('Shipping method'); ?></p>
					<p><strong>Free Shipping on orders more than Rs. 2000</strong></p>

                    <?php if(isset($this->formErrors['shipping_method']) && $this->formErrors['shipping_method']): ?>
                    <div class="onestepcheckout-error onestepcheckout-shipment-method-error">
                        <?php echo $this->__('Please choose a shipping method.'); ?>
                    </div>
                    <?php endif; ?>

                    <div class="onestepcheckout-shipping-method-block">
                        <?php echo $this->getChildHtml('choose-shipping-method'); ?>
                    </div>
                </div>
            <?php endif; ?>
        <?php endif; ?>

        <?php if(Mage::getStoreConfig('onestepcheckout/general/hide_payment_method')):?>
            <?php if(!empty($this->formErrors['payment_method'])): ?>
            <div class="onestepcheckout-error onestepcheckout-payment-method-error">
                <?php echo $this->__('Please choose a payment method.'); ?>
            </div>
            <?php endif; ?>
            <?php if(!empty($this->formErrors['payment_method_error'])): ?>
                <div class="onestepcheckout-error onestepcheckout-payment-method-error">
                    <?php echo $this->__('Please enter valid details below.'); ?>
                </div>
            <?php endif; ?>
            <?php echo $this->getChildHtml('choose-payment-method'); ?>
			<p id="hintText"></p>
			<div id="hintImg"></div>
        <?php else: ?>
            <p class="onestepcheckout-numbers onestepcheckout-numbers-<?php echo $step_counter++; ?>"><?php echo $this->__('Payment method'); ?></p>
            <?php if(isset($this->formErrors['payment_method']) && $this->formErrors['payment_method']): ?>
                <div class="onestepcheckout-error onestepcheckout-payment-method-error">
                    <?php echo $this->__('Please choose a payment method.'); ?>
                </div>

            <?php else: ?>
                <?php if(isset($this->formErrors['payment_method_error'])): ?>
                    <div class="onestepcheckout-error onestepcheckout-payment-method-error">
                        <?php echo $this->__('Please enter valid details below.'); ?>
                    </div>
                <?php endif; ?>
            <?php endif; ?>

            <?php echo $this->getChildHtml('choose-payment-method'); ?>

            <div class="tool-tip" id="payment-tool-tip" style="display:none;">
                <div class="btn-close">
                    <a href="javascript:void(0);" id="payment-tool-tip-close"><img src="<?php echo $this->getSkinUrl('images/btn_window_close.gif') ?>" alt="<?php echo $this->__('Close') ?>" /></a>
                </div>
                <div class="block-content">
                <img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>" alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>" />
                </div>
            </div>
        <?php endif; ?>
    </div>

    <div class="onestepcheckout-column-right">

        <p class="onestepcheckout-numbers onestepcheckout-numbers-4"><?php echo $this->__('Review your order'); ?></p>

        <div class="onestepcheckout-summary">
            <?php echo $this->getChildHtml('summary'); ?>
        </div>

        <?php if($this->settings['enable_discount']): ?>
        <div class="onestepcheckout-coupons">
            <div id="coupon-notice" style="display: none;"></div>
            <?php $_couponcode = $this->getQuote()->getCouponCode(); ?>
            <label for="id_couponcode"><?php echo $this->__('Coupon code:'); ?></label><br/>
            <input class="input-text" type="text" name="onestepcheckout-couponcode" id="id_couponcode" value="<?php echo $_couponcode; ?>" />
            <br/>
            <button id="onestepcheckout-coupon-add" class="form-button-alt" type="button"><span><?php echo $this->__('Apply Coupon'); ?></span></button>
            <button id="onestepcheckout-coupon-remove" class="form-button-alt" type="button" style="<?php if($_couponcode == '') { echo 'display: none;'; } ?>"><span><?php echo $this->__('Cancel Coupon'); ?></span></button>
            <script>
            Event.observe(window, 'load', function() {
                $('onestepcheckout-coupon-add').observe('click', function(e)    {

                    var coupon = $('id_couponcode').getValue();
                    var couponNotice = $('coupon-notice');

                    couponNotice.hide();

                    if(coupon == '')  {
                        alert('<?php echo $this->__('Please enter a valid coupon code.'); ?>');
                        return;
                    }

                    var url = '<?php echo $this->getUrl('onestepcheckout/ajax/add_coupon', array('_secure'=>true)); ?>';
                    var parameters = {code: coupon};
                    var shipping_methods = $$('dl.shipment-methods').first();
                    var payment_methods = $$('div.payment-methods').first();
                    var summary = $$('div.onestepcheckout-summary').first();

                    if(shipping_methods){
                        shipping_methods.update('<div class="loading-ajax">&nbsp;</div>');
                    }

                    if(payment_methods){
                        payment_methods.update('<div class="loading-ajax">&nbsp;</div>');
                    }

                    summary.update('<div class="loading-ajax">&nbsp;</div>');

                    new Ajax.Request(url, {
                        method: 'post',
                        parameters: parameters,
                        onSuccess: function(transport) {
                            if(transport.status == 200) {

                                var response = transport.responseText.evalJSON();

                                var url = '<?php echo $this->getUrl('onestepcheckout/ajax/set_methods_separate', array('_secure'=>true)); ?>';
                                var update_payments = <?php echo $this->settings['enable_update_payment_on_shipping'] ? 'true' : 'false'; ?>;

                                if(shipping_methods){
                                    shipping_methods.hide();
                                    shipping_methods.update(response.shipping_method);
                                    shipping_methods.show();
                                    $$('dl.shipment-methods input').invoke('observe', 'click', get_separate_save_methods_function(url, update_payments));
                                    $$('dl.shipment-methods input').invoke('observe', 'click', function() {
                                        $$('div.onestepcheckout-shipment-method-error').each(function(item) {
                                            new Effect.Fade(item);
                                        });
                                    });
                                }

                                if(payment_methods){
                                    payment_methods.hide();
                                    payment_methods.update(response.payment_method);
                                    payment_methods.show();

                                    paymentContainer = $('container_payment_method_' + payment.currentMethod)
                                    paymentForm = $('payment_form_' + payment.currentMethod)

                                    if(paymentContainer != null){
                                        paymentContainer.show();
                                    }
                                    if(paymentForm != null){
                                        paymentForm.show();
                                    }
                                    $$('div.payment-methods input[name^=payment\[method\]]').invoke('observe', 'click', get_separate_save_methods_function(url));
                                    $$('div.payment-methods input[name^=payment\[method\]]').invoke('observe', 'click', function() {
                                        $$('div.onestepcheckout-payment-method-error').each(function(item) {
                                            new Effect.Fade(item);
                                        });
                                    });
                                }

                                summary.hide();
                                summary.update(response.summary);
                                summary.show();

                                if(response.success) {

                                    couponNotice.update(response.message);
                                    couponNotice.removeClassName('error-msg');
                                    couponNotice.addClassName('success-msg');
                                    couponNotice.show();
                                    /* Show remove button */
                                    $('onestepcheckout-coupon-remove').show();
                                }
                                else    {

                                    couponNotice.update(response.message);
                                    couponNotice.removeClassName('success-msg');
                                    couponNotice.addClassName('error-msg');
                                    couponNotice.show();
                                    /* Hide remove button */
                                    $('onestepcheckout-coupon-remove').hide();
                                }
                            }
                        }
                    });
                });

                $('onestepcheckout-coupon-remove').observe('click', function(e) {

                    var coupon = $('id_couponcode').getValue();
                    var couponNotice = $('coupon-notice');

                    couponNotice.hide();

                    var url = '<?php echo $this->getUrl('onestepcheckout/ajax/add_coupon', array('_secure'=>true)); ?>';
                    var parameters = {code: coupon, remove: '1'};
                    var shipping_methods = $$('dl.shipment-methods').first();
                    var payment_methods = $$('div.payment-methods').first();
                    var summary = $$('div.onestepcheckout-summary').first();

                    if(shipping_methods){
                        shipping_methods.update('<div class="loading-ajax">&nbsp;</div>');
                    }

                    if(payment_methods){
                        payment_methods.update('<div class="loading-ajax">&nbsp;</div>');
                    }
                    summary.update('<div class="loading-ajax">&nbsp;</div>');

                    new Ajax.Request(url, {
                        method: 'post',
                        parameters: parameters,
                        onSuccess: function(transport)  {
                            if(transport.status == 200) {
                                var response = transport.responseText.evalJSON();

                                if(response.success){
                                    $('id_couponcode').setValue('')
                                    $('onestepcheckout-coupon-remove').hide();
                                }

                                var url = '<?php echo $this->getUrl('onestepcheckout/ajax/set_methods_separate', array('_secure'=>true)); ?>';
                                var update_payments = <?php echo $this->settings['enable_update_payment_on_shipping'] ? 'true' : 'false'; ?>;

                                if(shipping_methods){
                                    shipping_methods.hide();
                                    shipping_methods.update(response.shipping_method);
                                    shipping_methods.show();
                                    $$('dl.shipment-methods input').invoke('observe', 'click', get_separate_save_methods_function(url, update_payments));
                                    $$('dl.shipment-methods input').invoke('observe', 'click', function() {
                                        $$('div.onestepcheckout-shipment-method-error').each(function(item) {
                                            new Effect.Fade(item);
                                        });
                                    });
                                }

                                if(payment_methods){
                                    payment_methods.hide();
                                    payment_methods.update(response.payment_method);
                                    payment_methods.show();

                                    paymentContainer = $('container_payment_method_' + payment.currentMethod)
                                    paymentForm = $('payment_form_' + payment.currentMethod)

                                    if(paymentContainer != null){
                                        paymentContainer.show();
                                    }

                                    if(paymentForm != null){
                                        paymentForm.show();
                                    }
                                    $$('div.payment-methods input[name^=payment\[method\]]').invoke('observe', 'click', get_separate_save_methods_function(url));
                                    $$('div.payment-methods input[name^=payment\[method\]]').invoke('observe', 'click', function() {
                                        $$('div.onestepcheckout-payment-method-error').each(function(item) {
                                            new Effect.Fade(item);
                                        });
                                    });
                                }

                                summary.hide();
                                summary.update(response.summary);
                                summary.show();

                                couponNotice.hide();
                                couponNotice.update(response.message);
                                couponNotice.removeClassName('error-msg');
                                couponNotice.addClassName('success-msg');
                                couponNotice.show();
                            }
                        }
                    });
                });
            });
            </script>
        </div>
        <?php endif; ?>

        <?php if($this->settings['enable_giftcard']): ?>
        <div class="onestepcheckout-giftcards">
            <div id="giftcard-notice" style="display: none;"></div>
            <?php
            $_hasGiftCards = unserialize($this->getQuote()->getGiftCards());
            $_giftcardcode = $this->getQuote()->getgiftcardCode(); ?>
            <label for="id_giftcardcode"><?php echo $this->__('giftcard code:'); ?></label><br/>
            <input class="input-text" type="text" name="onestepcheckout-giftcardcode" id="id_giftcardcode" value="<?php echo $_giftcardcode; ?>" />
            <br/>
            <button id="onestepcheckout-giftcard-add" class="form-button-alt" type="button"><span><?php echo $this->__('Apply giftcard'); ?></span></button>
            <button id="onestepcheckout-giftcard-remove" class="form-button-alt" type="button" style="<?php if(empty($_hasGiftCards)) { echo 'display: none;'; } ?>"><span><?php echo $this->__('Cancel giftcard'); ?></span></button>
            <script>
            document.observe('dom:loaded', function() {
                $('onestepcheckout-giftcard-add').observe('click', function(e)    {
                    var giftcard = $('id_giftcardcode').getValue();
                    var giftcardNotice = $('giftcard-notice');
                    giftcardNotice.hide();
                    if(giftcard == '')    {
                        alert('<?php echo $this->__('Please enter a valid giftcard code.'); ?>');
                        return;
                    }

                    var url = '<?php echo $this->getUrl('onestepcheckout/ajax/add_giftcard', array('_secure'=>true)); ?>';
                    var parameters = {code: giftcard};
                    var shipping_methods = $$('dl.shipment-methods').first();
                    var payment_methods = $$('div.payment-methods').first();
                    var summary = $$('div.onestepcheckout-summary').first();

                    if(shipping_methods){
                        shipping_methods.update('<div class="loading-ajax">&nbsp;</div>');
                    }

                    if(payment_methods){
                        payment_methods.update('<div class="loading-ajax">&nbsp;</div>');
                    }
                    summary.update('<div class="loading-ajax">&nbsp;</div>');

                    new Ajax.Request(url+Math.random(1000), {
                        method: 'post',
                        parameters: parameters,
                        onSuccess: function(transport) {
                            if(transport.status == 200) {

                                var response = transport.responseText.evalJSON();

                                var url = '<?php echo $this->getUrl('onestepcheckout/ajax/set_methods_separate', array('_secure'=>true)); ?>';
                                var update_payments = <?php echo $this->settings['enable_update_payment_on_shipping'] ? 'true' : 'false'; ?>;

                                if(shipping_methods){
                                    shipping_methods.hide();
                                    shipping_methods.update(response.shipping_method);
                                    shipping_methods.show();
                                    $$('dl.shipment-methods input').invoke('observe', 'click', get_separate_save_methods_function(url, update_payments));
                                    $$('dl.shipment-methods input').invoke('observe', 'click', function() {
                                        $$('div.onestepcheckout-shipment-method-error').each(function(item) {
                                            new Effect.Fade(item);
                                        });
                                    });
                                }

                                if(payment_methods){
                                    //payment_methods.hide();
                                    payment_methods.update(response.payment_method);
                                    //payment_methods.show();

                                    paymentContainer = $('container_payment_method_' + payment.currentMethod)
                                    paymentForm = $('payment_form_' + payment.currentMethod)

                                    if(paymentContainer != null){
                                        paymentContainer.show();
                                    }
                                    if(paymentForm != null){
                                        paymentForm.show();
                                    }
                                    $$('div.payment-methods input[name^=payment\[method\]]').invoke('observe', 'click', get_separate_save_methods_function(url));
                                    $$('div.payment-methods input[name^=payment\[method\]]').invoke('observe', 'click', function() {
                                        $$('div.onestepcheckout-payment-method-error').each(function(item) {
                                            new Effect.Fade(item);
                                        });
                                    });
                                }

                                if(response.success) {
                                    summary.update(response.summary);
                                    giftcardNotice.update(response.message);
                                    giftcardNotice.removeClassName('error-msg');
                                    giftcardNotice.addClassName('success-msg');
                                    giftcardNotice.show();
                                    /* Show remove button */
                                    $('onestepcheckout-giftcard-remove').show();
                                }
                                else    {
                                    summary.update(response.summary);
                                    giftcardNotice.update(response.message);
                                    giftcardNotice.removeClassName('success-msg');
                                    giftcardNotice.addClassName('error-msg');
                                    giftcardNotice.show();
                                    /* Hide remove button */
                                    //$('onestepcheckout-giftcard-remove').hide();
                                }
                            }
                        }
                    });
                });

                $('onestepcheckout-giftcard-remove').observe('click', function(e) {
                    var giftcard = $('id_giftcardcode').getValue();
                    var giftcardNotice = $('giftcard-notice');
                    giftcardNotice.hide();
                    var url = '<?php echo $this->getUrl('onestepcheckout/ajax/add_giftcard', array('_secure'=>true)); ?>';
                    var parameters = {code: giftcard, remove: '1'};
                    var shipping_methods = $$('dl.shipment-methods').first();
                    var payment_methods = $$('div.payment-methods').first();
                    var summary = $$('div.onestepcheckout-summary').first();

                    if(shipping_methods){
                        shipping_methods.update('<div class="loading-ajax">&nbsp;</div>');
                    }

                    if(payment_methods){
                        payment_methods.update('<div class="loading-ajax">&nbsp;</div>');
                    }
                    summary.update('<div class="loading-ajax">&nbsp;</div>');

                    new Ajax.Request(url, {
                        method: 'post',
                        parameters: parameters,
                        onSuccess: function(transport)  {
                            if(transport.status == 200) {
                                var response = transport.responseText.evalJSON();

                                var url = '<?php echo $this->getUrl('onestepcheckout/ajax/set_methods_separate', array('_secure'=>true)); ?>';
                                var update_payments = <?php echo $this->settings['enable_update_payment_on_shipping'] ? 'true' : 'false'; ?>;

                                if(shipping_methods){
                                    shipping_methods.hide();
                                    shipping_methods.update(response.shipping_method);
                                    shipping_methods.show();
                                    $$('dl.shipment-methods input').invoke('observe', 'click', get_separate_save_methods_function(url, update_payments));
                                    $$('dl.shipment-methods input').invoke('observe', 'click', function() {
                                        $$('div.onestepcheckout-shipment-method-error').each(function(item) {
                                            new Effect.Fade(item);
                                        });
                                    });
                                }

                                if(payment_methods){
                                    $$('div.payment-methods input[name^=payment\[method\]]').invoke('observe', 'click', get_separate_save_methods_function(url));
                                    $$('div.payment-methods input[name^=payment\[method\]]').invoke('observe', 'click', function() {
                                        $$('div.onestepcheckout-payment-method-error').each(function(item) {
                                            new Effect.Fade(item);
                                        });
                                    });
                                    payment_methods.hide();
                                    payment_methods.update(response.payment_method);
                                    payment_methods.show();

                                    paymentContainer = $('container_payment_method_' + payment.currentMethod)
                                    paymentForm = $('payment_form_' + payment.currentMethod)

                                    if(paymentContainer != null){
                                        paymentContainer.show();
                                    }
                                    if(paymentForm != null){
                                        paymentForm.show();
                                    }
                                }

                                if(response.success){
                                    $('id_giftcardcode').setValue('')
                                    $('onestepcheckout-giftcard-remove').hide();
                                }
                                var summary = $$('div.onestepcheckout-summary').first();

                                summary.hide();
                                summary.update(response.summary);
                                summary.show();

                                giftcardNotice.hide();
                                giftcardNotice.update(response.message);
                                giftcardNotice.removeClassName('error-msg');
                                giftcardNotice.addClassName('success-msg');
                                giftcardNotice.show();
                            }
                        }
                    });
                });
            });
            </script>
        </div>
        <?php endif; ?>

        <?php if($this->settings['enable_comments']): ?>
            <div class="onestepcheckout-comments">
                <label for="id_comments"><?php echo $this->__('Comments'); ?></label><br/>
                <textarea id="id_comments" name="onestepcheckout_comments"><?php if(isset($_POST['onestepcheckout_comments'])) { echo $_POST['onestepcheckout_comments']; } ?></textarea>
            </div>
        <?php endif; ?>

        <?php if($this->settings['enable_gift_messages']): ?>
            <div id="onestepcheckout-giftmessages">
            <div class="onestepcheckout-giftmessagecontainer">
            <?php echo $this->helper('onestepcheckout/message')->getInline('onepage_checkout', $this->getQuote(), $this->getDontDisplayContainer()) ?>
            </div>
            </div>
        <?php endif; ?>

        <?php $customerEmail = (($this->isCustomerLoggedIn())) ? $this->getQuote()->getCustomer()->getEmail() : false ;?>
        <?php if($this->settings['enable_newsletter'] && !$this->isSubScribed($customerEmail)): ?>
            <div class="onestepcheckout-enable-newsletter">
                <input type="checkbox" id="id_subscribe_newsletter" name="subscribe_newsletter" value="1" <?php if($this->settings['newsletter_default_checked']): ?>checked="checked"<?php endif; ?> />
                <label for="id_subscribe_newsletter"><?php echo $this->__('Subscribe to our newsletter'); ?></label>
            </div>
        <?php endif; ?>

        <?php $_extraProductsHelper = Mage::helper('onestepcheckout/extraproducts'); ?>
            <?php if($_extraProductsHelper->hasExtraProducts()): ?>
            <div class="onestepcheckout-extraproducts">
                <ul>
                <?php foreach($_extraProductsHelper->getExtraProducts() as $product): ?>
                    <li><input type="checkbox" class="onestepcheckout-extra-product"
                    <?php if($_extraProductsHelper->productInCart($product->getId())): ?>
                        checked="checked" <?php endif; ?>
                        name="extra_products_<?php echo $product->getId(); ?>"
                        id="id_extra_product_<?php echo $product->getId(); ?>" /> &nbsp;
                    <label for="id_extra_product_<?php echo $product->getId(); ?>"> <?php echo $product->getName(); ?>
                    <span><?php echo Mage::helper('checkout')->formatPrice($product->getPrice()); ?></span>
                    </label></li>
                    <?php endforeach; ?>
                </ul>
            </div>

            <script>
            Event.observe(window, 'load', function() {
                $$('input.onestepcheckout-extra-product').invoke('observe', 'click', function(e) {
                    var id_temp = e.element().id.split('id_extra_product_');
                    if(id_temp.length == 2) {
                        var product_id = id_temp[1];
                        var url = '<?php echo $this->getUrl('onestepcheckout/ajax/add_extra_product'); ?>';
                        var parameters = {
                            product_id: product_id
                        }

                        if(!e.element().checked) {


                            parameters['remove'] = 1;
                        }

                        var summary = $$('div.onestepcheckout-summary').first();
                        summary.update('<div class="loading-ajax">&nbsp;</div>');

                        new Ajax.Request(url, {
                            method: 'post',
                            parameters: parameters,
                            onSuccess: function(transport)  {
                                summary.update(transport.responseText);
                            }
                        });
                   };
                });
            });
        </script>
        <?php endif; ?>

        <?php
        /**
         * Feedbackdropdown start
         */
        ?>
        <?php if(!empty($this->settings['feedback']['enable_feedback']) && !empty($this->settings['feedback']['feedback_values'])):?>
            <?php
                $selectedFeedBackFields = $this->getRequest()->getPost('onestepcheckout-feedback', false);
                $feedbackValues = unserialize($this->settings['feedback']['feedback_values']);
            ?>
            <div class="onestepcheckout-feedback" id="">
                <label for="id_feedback"><?php echo $this->__('How did you hear about us?'); ?></label><br>
                <select style="" name="onestepcheckout-feedback" id="id_feedback" defaultvalue="">
                    <option value=""><?php echo $this->__('Please choose'); ?></option>
                    <?php foreach($feedbackValues as $value => $label):
                        $selected= (!empty($selectedFeedBackFields) && $selectedFeedBackFields == $value) ? ' selected' : '';
                    ?>
                    <option value="<?php echo $value?>" <?php echo $selected;?>><?php echo $label['value']?></option>
                    <?php endforeach;?>
                    <?php if(!empty($this->settings['feedback']['enable_feedback_freetext'])):
                        $selected= (empty($feedbackValues[$selectedFeedBackFields]) && $selectedFeedBackFields != '') ? ' selected' : '';
                    ?>
                    <option value="freetext" <?php echo $selected;?>><?php echo $this->__('Other'); ?></option>
                    <?php endif;?>
                </select>
            </div>
            <?php if(!empty($this->settings['feedback']['enable_feedback_freetext'])):?>
                <script type="text/javascript">
                    $('id_feedback').observe('change', function (event){
                        if(this.getValue() == 'freetext'){
                            $('id_feedback_freetext_div').show();
                        } else {
                            $('id_feedback_freetext_div').hide();
                        }
                    });
                </script>
                <div id='id_feedback_freetext_div' class="onestepcheckout-feedback-freetext"<?php echo ((!empty($selectedFeedBackFields) && $selectedFeedBackFields == 'freetext') ? '' : ' style="display: none;"'); ?>>
                    <label for="id_feedback_freetext"><?php echo $this->__('Please specify:'); ?></label><br/>
                    <textarea id="id_feedback_freetext" name="onestepcheckout-feedback-freetext"><?php echo $this->getRequest()->getPost('onestepcheckout-feedback-freetext', false);?></textarea>
                </div>
            <?php endif; ?>
        <?php endif; ?>
        <?php
        /**
         * Feedbackdropdown end
         */
        ?>

        <?php if($this->settings['enable_terms']): //deprecated?>
            <div class="onestepcheckout-enable-terms">
                <?php

                if(isset($this->formErrors['terms_error']) && $this->formErrors['terms_error']) {
                    $terms_error = true;
                }
                else    {
                    if($_SERVER['REQUEST_METHOD'] == 'POST')    {
                        $terms_error = false;
                    }
                    else    {
                        $terms_error = true;
                    }
                }
                ?>

                <input class="required-entry" type="checkbox" id="id_accept_terms" name="accept_terms" value="1" <?php if(!$terms_error) echo "checked=\"checked\""; ?> />
                <label for="id_accept_terms"><?php echo $this->__('I accept the <a id="onestepcheckout-toc-link" target="_blank" href="javascript:void(0);">Terms and Conditions</a>'); ?></label>

                <?php if(isset($this->formErrors['terms_error']) && $this->formErrors['terms_error']): ?>
                <div class="onestepcheckout-error onestepcheckout-terms-error">
                    <?php echo $this->__('You must accept our terms to continue.'); ?>
                </div>
                <?php endif; ?>

            </div>
        <?php endif; ?>

        <?php
        /**
         * Default magento agreements
         */
        ?>
        <?php if($this->settings['enable_default_terms']): ?>
            <?php if(!empty($this->formErrors['agreements_error'])):?>
            <div class="onestepcheckout-error onestepcheckout-terms-error">
                <?php echo $this->__('Please agree to all the terms and conditions before placing the order.'); ?>
            </div>
            <?php endif;?>
            <?php echo $this->getChildHtml('agreements') ?>
            <script type="text/javascript">
                    var termsmodals = new Object;
                    <?php if($this->settings['enable_textarea']):?>
                        $$('div.agreement-content').each(
                                function(element){
                                    element.id = 'agreement-div-' + element.up('li').down('input').id;
                                    $$('body')[0].insert(element);
                                });
                    <?php endif;?>

                    $$('.checkout-agreements li p input').each(
                        function(elem){
                            elem.addClassName('required-entry');
                            <?php if($this->settings['enable_textarea']):?>
                            window.termsmodals[elem.id] = new Control.Modal($('agreement-div-' + elem.id),{
                                overlayOpacity: 0.75,
                                className: 'modal',
                                fade: true,
                                closeOnClick: true,
                                height: 400,
                                width: 700
                            });
                            <?php endif;?>
                        }
                    );
                    <?php if($this->settings['enable_textarea']):?>
                    $$('.checkout-agreements li p label').each(
                        function(elem){
                            elem.up().insert('<a href="javascript:void(0);" onclick="termsmodals[\'' + elem.htmlFor + '\'].open();">' + elem.innerHTML + '</a>');
                            elem.hide();
                        }
                    );
                    <?php endif;?>
            </script>
        <?php endif;?>
        <?php
        /**
         * Default magento agreements end
         */
        ?>


        <div class="onestepcheckout-place-order-wrapper">
            <button type="button" title="<?php echo $this->__('Place order now'); ?>" id="onestepcheckout-place-order" class="large orange onestepcheckout-button onestepcheckout-place-order" onclick="javascript:void(0);"><span><span><?php echo $this->__('Place order now'); ?></span></span></button>
        </div>
    </div>
    <div style="clear: both;">&nbsp;</div>
</div>
</fieldset>
</form>

<?php if(!$this->isCustomerLoggedIn() && $helper->showLoginLink()): ?>
    <?php echo $this->getChildHtml('login-popup'); ?>
<?php endif; ?>

<?php if($helper->isValidateEmail()): ?>
<script>
$('billing:email').observe('blur', function(e)    {
    var url = '<?php echo $this->getUrl('onestepcheckout/ajax/check_email', array('_secure'=>true)); ?>';
    var email = e.element().getValue();
    var parameters = { email: email };

    new Ajax.Request(url, {
        parameters: parameters,
        onComplete: function(response)  {
            if(response.status == 200)  {
                var result = response.responseText.evalJSON().result;
                if(result == 'invalid') {
                    $('onestepcheckout-email-error-message').update('<?php echo $this->__('Invalid email address.'); ?>');
                    $('onestepcheckout-email-error').show();
                }
                else if(result == 'exists') {
                    <?php if($this->settings['registration_order_without_password']): ?>
                    // Remove the password fields if the email exists in database
                    $('onestepcheckout-li-password').hide();
                    <?php else: ?>

                    $('onestepcheckout-email-error-message').update('<?php echo $this->__('Email address already registered. Please <a href="javascript:void(0);" onclick="login_popup.show(); return false;">login now</a> or use a different email address.'); ?>');
                    $('onestepcheckout-email-error').show();
                    // Ask the user to login or change email address
                    //login_popup.show();
                    $('id_onestepcheckout_username').value = email;
                    <?php endif; ?>
                }
                else    {
                    $('onestepcheckout-email-error').hide();
                    $('onestepcheckout-li-password').show();
                }
            }
        }
    })

});
Validation.add('validate-email', '<?php echo $this->__('This is a required field.') ?>', function(v) {
    var url = '<?php echo $this->getUrl('onestepcheckout/ajax/check_email', array('_secure'=>true)); ?>';
    var email = v;
    var parameters = { email: email };
    var value = Validation.get('IsEmpty').test(v) || /^([a-z0-9,!\#\$%&'\*\+\/=\?\^_`\{\|\}~-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9,!\#\$%&'\*\+\/=\?\^_`\{\|\}~-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*@([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z0-9-]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*\.(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]){2,})$/i.test(v)

    new Ajax.Request(url, {
        parameters: parameters,
        asynchronous: false,
        onComplete: function(response)  {
            if(response.status == 200)  {
                var result = response.responseText.evalJSON().result;
                if(result == 'invalid') {
                    value =  false;
                } else if(result == 'exists') {
                    <?php if($this->settings['registration_order_without_password']): ?>
                    $('onestepcheckout-li-password').hide();
                    <?php else: ?>
                    $('onestepcheckout-email-error-message').update('<?php echo $this->__('Email address already registered. Please <a href="javascript:void(0);" onclick="login_popup.show(); return false;">login now</a> or use a different email address.'); ?>');
                    $('onestepcheckout-email-error').show();
                    $('id_onestepcheckout_username').value = email;
                    value =  false;
                    <?php endif; ?>
                }
            }
        }
    })
    return value;
});
</script>
<?php endif; ?>





<?php if($this->settings['enable_terms']): ?>
<div id="onestepcheckout-toc-popup" style="display: none;">

    <div class="onestepcheckout-popup-wrapper">
        <div class="onestepcheckout-popup-wrapper-inner">
            <h1><?php echo $this->settings['terms_title']; ?></h1>

            <div class="onestepcheckout-toc-terms">
                <?php echo $this->settings['terms_contents']; ?>
            </div>

            <p class="close"><a href="javascript:void(0);"><?php echo $this->__('Close'); ?></a></p>
        </div>
    </div>
    <div class="onestepcheckout-popup-footer">&nbsp;</div>
</div>

<script>
Event.observe(window, 'load', function() {

    var termsPopup = new Control.Modal($('onestepcheckout-toc-popup'), {
        overlayOpacity: 0.65,
        fade: true,
        fadeDuration: 0.3
    });

    $('onestepcheckout-toc-link').observe('click', function(e) {
        e.preventDefault();
        termsPopup.open();
    });

    $$('div#onestepcheckout-toc-popup p.close a').invoke('observe', 'click', function(e) {
        e.preventDefault();
        termsPopup.close();
    });

});

/*
var popup;
Event.observe(window, 'load', function() {
    popup = new OneStepCheckout_Popup('onestepcheckout-toc-popup','onestepcheckout-toc-link', 'div#onestepcheckout-toc-popup p.close a');
});
*/
</script>
<?php endif; ?>





<script>
<?php if($this->hasFormErrors()): ?>
if($$('div.input-error').length > 0) {
    var input = $$('div.input-error')[0].select('input');
    if(input.length == 1)   {
        input[0].focus();
    }
}
<?php endif; ?>
</script>

<?php if(!$this->settings['exclude_region']): ?>
<script type="text/javascript">countryRegions = <?php echo $this->helper('directory')->getRegionJson() ?></script>
<script type="text/javascript">
//<![CDATA[
    var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', countryRegions, undefined, 'billing:postcode');

    <?php if($this->settings['enable_different_shipping'] && !$this->isVirtual()): ?>
    var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', countryRegions, undefined, 'shipping:postcode');
    <?php endif; ?>
//]]>
</script>
<?php endif; 
$totals = Mage::getSingleton('checkout/cart')->getQuote()->getTotals();
$subtotal = $totals["subtotal"]->getValue();
?>
<script type="text/javascript">

function UpdateShipMethod() {
	var subtotal=<?php echo $subtotal; ?>;
	
	j('#s_method_shippingrates_Freeshipping').hide();
	j('#s_method_shippingrates_Flatrate').hide();
	
	j('label[for="s_method_shippingrates_Freeshipping"]').hide();
	j('label[for="shipping_shippingrates_Freeshipping"]').hide();
	j('label[for="s_method_shippingrates_Flatrate"]').hide();
	j('label[for="shipping_shippingrates_Flatrate"]').hide();
	j('#container_payment_method_cashondelivery').hide();


	if(j('#p_method_Avenues_standard').is(':checked')) {
					
		//j('#s_method_shippingrates_Freeshipping').attr("checked","checked");
		//j('#s_method_shippingrates_Flatrate').removeAttr('checked');
		
		//j('label[for="shipping_shippingrates_Freeshipping"]').show();
		if(subtotal > 2000) {
			j('#s_method_shippingrates_Freeshipping').attr("checked","checked");
			j('#s_method_shippingrates_Flatrate').removeAttr('checked');
			
			j('label[for="shipping_shippingrates_Freeshipping"]').show();
		

		} else {		
			j('#s_method_shippingrates_Flatrate').attr("checked","checked");
			j('#s_method_shippingrates_Freeshipping').removeAttr('checked');
			
			j('label[for="shipping_shippingrates_Flatrate"]').show();
	
		}
		
		
	} 
	if(j('#p_method_cashondelivery').is(':checked')) {
		
		if(subtotal > 2000) {
			j('#s_method_shippingrates_Freeshipping').attr("checked","checked");
			j('#s_method_shippingrates_Flatrate').removeAttr('checked');
			
			j('label[for="shipping_shippingrates_Freeshipping"]').show();
		

		} else {		
			j('#s_method_shippingrates_Flatrate').attr("checked","checked");
			j('#s_method_shippingrates_Freeshipping').removeAttr('checked');
			
			j('label[for="shipping_shippingrates_Flatrate"]').show();
	
		}
		j('#container_payment_method_cashondelivery').show();
		j('#container_payment_method_cashondelivery fieldset').show();
		j('#payment_form_cashondelivery').show();
   } 
}

Event.observe(window, 'load', function() {
    if ($$('div.shopping-cart-totals').length == 1) {
    }
    else    {

        already_placing_order = false;
        review = false;

        /* Handle place order click event */
        $$('.onestepcheckout-place-order').each(function(elem){
            elem.observe('click', function(e)   {
                Event.stop(e);

               // First validate the form
                var form = new VarienForm('onestepcheckout-form');

                if(!form.validator.validate())  {
                    Event.stop(e);
                } else {

                    if(!already_placing_order && $$('.loading-ajax').length <= 0 ) {
                    <?php if(!empty($helper->settings['addressreview']['enable_addressreview'])):?>
                        var addressTemplates = {
                            shipping: '<?php echo str_replace("\r", '', str_replace("\n", '', $helper->settings['addressreview']['shipping_template']));?>',
                            billing: '<?php echo str_replace("\r", '', str_replace("\n", '', $helper->settings['addressreview']['billing_template']));?>'
                        };
                        addressPreview(addressTemplates, 'addressreview');
                        if(!review){
                            review = true;
                            reviewmodal.container = $('addressreview');
                            reviewmodal.open();
                            reviewmodal.observe('beforeClose',function(){
                                review = false;
                            });
                            return true;
                            Event.stop(e);
                        } else {
                            reviewmodal.close();
                        }
                    <?php endif;?>
                        already_placing_order = true;

                        var submitelement = $('onestepcheckout-place-order');

                        var loaderelement = new Element('div').
                            addClassName('onestepcheckout-place-order-loading').
                            update('<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif'); ?>" />&nbsp;&nbsp;<?php echo $this->__('Please wait, processing your order...'); ?>');

                        submitelement.parentNode.appendChild(loaderelement);

                        /* Disable button to avoid multiple clicks */
                        submitelement.removeClassName('orange').addClassName('grey');
                        submitelement.disabled = true;

                        /* Submit the form */
                        $('onestepcheckout-form').submit();
                    }
                }
            });
        });


        // This is a separate page
        var url = '<?php echo $this->getUrl('onestepcheckout/ajax/set_methods_separate', array('_secure'=>true)); ?>';
        var update_payments = <?php echo $this->settings['enable_update_payment_on_shipping'] ? 'true' : 'false'; ?>;

        $$('dl.shipment-methods input').invoke('observe', 'click', get_separate_save_methods_function(url, update_payments));
		$$('div.payment-methods input[name="payment\[method\]"]').invoke('observe', 'click', function() {
            UpdateShipMethod();
        });
		
        $$('div.payment-methods input[name="payment\[method\]"]').invoke('observe', 'click', get_separate_save_methods_function(url));

        $$('div.payment-methods input[name="payment\[method\]"]').invoke('observe', 'click', function() {
            $$('div.onestepcheckout-payment-method-error').each(function(item) {
                new Effect.Fade(item);
            });
        });

        $$('dl.shipment-methods input').invoke('observe', 'click', function() {
            $$('div.onestepcheckout-shipment-method-error').each(function(item) {
                new Effect.Fade(item);
            });
        });

        var has_hidden_terms = false;

        if($('id_accept_terms') != null)    {

            $('id_accept_terms').observe('click', function(e)   {
                var element = e.element();


                if(element.checked) {
                    $$('div.onestepcheckout-terms-error').each(function(item) {
                        new Effect.Fade(item);
                        has_hidden_terms = true;
                    });
                }
                else    {
                    if(has_hidden_terms)    {
                        $$('div.onestepcheckout-terms-error').each(function(item) {
                            new Effect.Appear(item);
                            has_hidden_terms = false;
                        });
                    }
                }
            });
        }
    }

    var form = $('onestepcheckout-form');

    /* Highlight selected payment method if one set */
    if($RF(form, 'payment[method]') != null)    {
        try {
            var payment_method = $RF(form, 'payment[method]');
            $('container_payment_method_' + payment_method).show();
            $('payment_form_' + payment_method).show();
        } catch(err)    {

        }
    }

    /* Set default shipping method if not set */
    if($RF(form, 'shipping_method') == null)    {
        try {
            var method = '<?php echo $this->_getDefaultShippingMethod(); ?>';
            if(method != '')    {
                $('s_method_' + method).checked = true;
                get_separate_save_methods_function(url);
            }
        } catch(err)    {

        }
    }
   //submit what's available on load
   
   get_separate_save_methods_function(url)();

<?php if($this->differentShippingAvailable()): ?>
    $('billing:use_for_shipping_yes').observe('click', function(e)  {
        var element = e.element();
        if(element.checked){
            $('shipping_address').hide();
        } else {
            if($('shipping-address-select') && $('shipping-address-select').value == ''){
                $('shipping_address_list').show()
            }
            $('shipping_address').show();
            <?php if(!$this->isCustomerLoggedIn()):?>
            $('shipping_address_list').show()
            <?php endif;?>
            <?php if($this->isCustomerLoggedIn()):?>
            if(!$('shipping-address-select') && $('shipping_address_list').getStyle('display')=='none'){
                $('shipping_address_list').show()
            }
            <?php endif;?>
			
        }

        <?php if($this->settings['enable_ajax_save_billing']): ?>
        get_save_billing_function('<?php echo $this->getUrl('onestepcheckout/ajax/save_billing', array('_secure'=>true)); ?>', '<?php echo $this->getUrl('onestepcheckout/ajax/set_methods_separate', array('_secure'=>true)); ?>', <?php echo $this->settings['enable_update_payment_on_shipping'] ? 'true' : 'false'; ?>, 'true')();
        <?php endif; ?>
		
    });
    <?php endif; ?>

    <?php if($this->settings['enable_ajax_save_billing']): ?>

    var url_save_billing = '<?php echo $this->getUrl('onestepcheckout/ajax/save_billing', array('_secure'=>true)); ?>';
    var url_set_methods = '<?php echo $this->getUrl('onestepcheckout/ajax/set_methods_separate', array('_secure'=>true)); ?>';
    var update_payments = <?php echo $this->settings['enable_update_payment_on_shipping'] ? 'true' : 'false'; ?>;
    var update_on_initial = false;

    var shipping_address_select = $('shipping-address-select');
    var billing_address_select = $('billing-address-select');
    var euvat = $('euvat_action_validate_taxvat');

    if(euvat !== null){
        euvat.observe('click', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
    }
    var billing_region_id = $('billing:region_id');
    var shipping_region_id = $('shipping:region_id');

    <?php if($this->hasAjaxSaveBillingField('country')): ?>

        $('billing:country_id').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));

        <?php if($this->differentShippingAvailable()): ?>
        $('shipping:country_id').observe('change', get_save_billing_function(url_save_billing, url_set_methods, update_payments));
            <?php if($this->isCustomerLoggedIn()): ?>
            if(shipping_address_select !== null) {
                Event.stopObserving('shipping-address-select', 'change');
                $('shipping-address-select').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
            }
            <?php endif; ?>
        <?php endif; ?>
        <?php if($this->isCustomerLoggedIn()): ?>
        if(billing_address_select !== null) {
            Event.stopObserving('billing-address-select', 'change');
            $('billing-address-select').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
        }
        <?php endif; ?>
    <?php endif; ?>


    <?php if($this->hasAjaxSaveBillingField('state/region')): ?>
    if(billing_region_id != null){
        $('billing:region_id').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
        $('billing:region').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
    }

        <?php if($this->differentShippingAvailable()): ?>
        if(shipping_region_id != null){
            $('shipping:region_id').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
            $('shipping:region').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
        }
            <?php if($this->isCustomerLoggedIn()): ?>
            if(shipping_address_select !== null) {
                Event.stopObserving('shipping-address-select', 'change');
                $('shipping-address-select').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
            }
            <?php endif; ?>
        <?php endif; ?>
        <?php if($this->isCustomerLoggedIn()): ?>
        if(billing_address_select !== null) {
            Event.stopObserving('billing-address-select', 'change');
            $('billing-address-select').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
        }
        <?php endif; ?>

    <?php endif; ?>



    <?php if($this->hasAjaxSaveBillingField('postcode')): ?>
    $('billing:postcode').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));

        <?php if($this->differentShippingAvailable()): ?>
        $('shipping:postcode').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
            <?php if($this->isCustomerLoggedIn()): ?>
            if(shipping_address_select !== null) {
                Event.stopObserving('shipping-address-select', 'change');
                $('shipping-address-select').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
            }
            <?php endif; ?>
        <?php endif; ?>
        <?php if($this->isCustomerLoggedIn()): ?>
        if(billing_address_select !== null) {
            Event.stopObserving('billing-address-select', 'change');
            $('billing-address-select').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
        }
        <?php endif; ?>

    <?php endif; ?>

    <?php if($this->hasAjaxSaveBillingField('city')): ?>
    $('billing:city').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));

        <?php if($this->differentShippingAvailable()): ?>
        $('shipping:city').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
            <?php if($this->isCustomerLoggedIn()): ?>
            if(shipping_address_select !== null) {
                Event.stopObserving('shipping-address-select', 'change');
                $('shipping-address-select').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
            }
            <?php endif; ?>
        <?php endif; ?>
        <?php if($this->isCustomerLoggedIn()): ?>
        if(billing_address_select !== null) {
            Event.stopObserving('billing-address-select', 'change');
            $('billing-address-select').observe('change', get_save_billing_function(url_save_billing, url_set_methods,update_payments));
        }
        <?php endif; ?>

    <?php endif; ?>


    <?php endif; ?>

});

if($('payment-tool-tip-close')){
    Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
}

</script>


<?php endif; ?>

<div id="onestepcheckout_popup_overlay" style="display: none;">&nbsp;</div>


<div id="loading-process" style="display: none;"></div>
