<?php
$_coreHelper = $this->helper('core');
$checkoutHelper = Mage::helper('onestepcheckout/checkout');
?>

<table class="onestepcheckout-summary">
    <thead>
        <tr>
            <th class="name"><?php echo $this->__('Product'); ?></th>
            <th class="qty"><?php echo $this->__('Qty'); ?></th>
            <th class="total"><?php echo $this->__('Subtotal'); ?></th>
        </tr>
    </thead>
    <?php echo $this->renderTotals(); ?>
	<?php echo $this->renderTotals('footer'); ?>
</table>

<table class="onestepcheckout-totals">
    <?php foreach($this->getTotals() as $total): ?>
    <?php if(!$total->getTitle()){continue;}?>
        <?php
        $fullInfo = $total->getFullInfo();

        if(!empty($fullInfo) && $checkoutHelper->settings['display_full_tax']):
            foreach ($fullInfo as $info):
                $rates = current($info['rates']);
                $amount = $info['amount'];
        ?>
            <tr>
                <td class="title"><?php echo $rates['title'] ?> (<?php echo $rates['percent'] ?>%)</td><td class="value"><?php echo $this->helper('checkout')->formatPrice($amount); ?></td>
            </tr>
        <?php endforeach;
        endif;?>
    <tr<?php if($total->getCode() == 'grand_total'): ?> class="grand-total"<?php endif; ?>>
        <td class="title">
            <?php

            $code = $total->getCode();
            $value = $total->getValue();

            if($code == 'subtotal')    {
                $total_name = $this->__('Subtotal');
            }
            elseif($code == 'shipping')    {
                $total_name = $this->__('Shipping');
                if($checkoutHelper->settings['display_tax_included'])   {
                    $value += $this->getQuote()->getShippingAddress()->getShippingTaxAmount();
                }
                            }
            elseif($code == 'grand_total')    {
                $total_name = $this->__('Grand total');
            }
            else    {
                $total_name = $total->getTitle();
            }

            echo $total_name;

            ?>
        </td>
        <td class="value">
            <?php echo $this->helper('checkout')->formatPrice($value); ?>
        </td>
    </tr>
    <?php endforeach; ?>
</table>
<script type="text/javascript">
//<![CDATA[
var total = <?php echo $this->getGrandTotal();?>;
    if(payment.reloadcallback){
        var url = '<?php echo $this->getUrl('onestepcheckout/ajax/paymentrefresh', array('_secure'=>true)); ?>';
        paymentrefresh(url);
        payment.countreload = 0;
        payment.reloadcallback = false;
    }
//]]>
</script>
